name: .NET

on:
  push:
    branches:    
      - 'master'
  schedule:
    - cron: '0 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Build
      env:
        ProjectNamePrefix: FluffySpoon.
        GitHubUsername: ffMathy
        NuGetKey: ${{ secrets.NuGetKey }}
        NpmAuthToken: ${{ secrets.NpmAuthToken }}
        GitHubPersonalAccessToken: ${{ secrets.GitHubPersonalAccessToken }}
        
        # specific to some projects
        NgrokOptions__AuthToken: ${{ secrets.NgrokOptionsAuthToken }}
        
      run: |
        cd src
        dotnet restore
        dotnet build
        cd FluffySpoon.Publisher.Sample
        dotnet run
